plugins:
  discourse_donations_enabled:
    default: false
    client: true
  discourse_donations_secret_key:
    default: ''
    client: false
  discourse_donations_public_key:
    default: ''
    client: true
  discourse_donations_description:
    client: true
    default: ''
  discourse_donations_currency:
    client: true
    default: "US dollar (USD)"
    type: enum
    choices:
      - Australian dollar (AUD)
      - Canadian dollar (CAD)
      - Euro (EUR)
      - Japanese yen (JPY)
      - Pound sterling (GBP)
      - US dollar (USD)
  discourse_donations_page_description:
    client: true
    default: ''
