plugins:
  discourse_donations_enabled:
    default: false
    client: true
  discourse_donations_secret_key:
    default: ''
    client: false
  discourse_donations_public_key:
    default: ''
    client: true
  discourse_donations_description:
    client: true
    default: ''
  discourse_donations_currency:
    client: true
    default: "USD"
    type: enum
    choices:
      - AUD
      - CAD
      - EUR
      - JPY
      - GBP
      - USD
  discourse_donations_page_description:
    client: true
    default: ''
